# ===============================
# DATABASE POSTGRESQL
# ===============================

spring:
  datasource:
    driverClassName: org.postgresql.Driver

    url: ${JDBC_DATASOURCE_URL}
    username: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}
    #initialization-mode : always
    #url : jdbc:postgresql://localhost:5432/Alexa
    #username: postgres
    #password: 123

---

# ===============================
# JPA / HIBERNATE
# ===============================

spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

        temp:
          use_jdbc_metadata_defaults: false

---

# ===============================
# FILE SIZE
# ===============================

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 5MB

