# ===============================
# DATABASE POSTGESQL
# ===============================

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    #jdbc:postgresql://localhost:5432/Alexa
    #username: postgres
    #password: 123
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

---

# ===============================
# JPA / HIBERNATE
# ===============================

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

        temp:
          use_jdbc_metadata_defaults: false



---
